SET REFERENTIAL_INTEGRITY FALSE;
TRUNCATE TABLE departments RESTART IDENTITY;
TRUNCATE TABLE user_role RESTART IDENTITY;
TRUNCATE TABLE users RESTART IDENTITY;
TRUNCATE TABLE roles RESTART IDENTITY;
